config/routes.rb
Wefridgerator::Application.routes.draw do
  get "invitees/new"
  root 'users#new'

  resources :users

  resource :session, only: [:new, :create, :destroy]

  resources :static_pages 
  
  post "categories/:category_id/items/:id/update" => "items#update_item", as: :update_item
  get "categories/:id/items/new_item" => "items#new_container_item", as: :new_container_item
  get "categories/:id/items/new_sl" => "items#new_shopping_list_item", as: :new_shopping_list_item
  # get "categories/api/"  => "categories#nothing"
  get "groups/:id/api/items" => "categories#item_json"
  #delete "containers/:id/api/items" => "items#destroy"
  delete "categories/:category_id/items/:id" => "items#destroy"
  post "categories/:id/items/speech" => "items#create_speech", as: :new_speech_item


  resources :groups do
    resources :invitees
    resources :user_groups
    resources :receipts
    resources :categories
    resources :arts
    resources :messages
  end

  resources :categories do
    resources :items, only: [:index, :show, :create, :edit, :update, :destroy]
  end

end

app/models/art.rb
class Art < ActiveRecord::Base
  belongs_to :user
  belongs_to :container
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items
  belongs_to :group
end

app/models/chatroom.rb
class Chatroom < ActiveRecord::Base
	has_many :messages

  belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :shopping_lists
	has_many :categories
	has_many :receipts
  has_many :arts
  has_many :invitees
  has_many :items, through: :categories
  has_many :messages
  # belongs_to :user_groups
  has_many :user_groups
	has_many :users, through: :user_groups

end

app/models/invitee.rb
class Invitee < ActiveRecord::Base
  belongs_to :group
end

app/models/item.rb
class Item < ActiveRecord::Base
  
  belongs_to :category
  belongs_to :user
  belongs_to :group

  
  # validates :name, presence: true
  # validates :quantity, {presence: true, numericality: true}
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/shopping_list.rb
class ShoppingList < ActiveRecord::Base
	has_many :items
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :arts
	has_many :receipts
	has_many :messages
	has_many :shopping_lists
  has_many :items
  
  # belongs_to :user_groups
  has_many :user_groups
  has_many :groups, through: :user_groups

	has_secure_password 

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/invitees_helper.rb
module InviteesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/partials/_create_group.html.erb
<div class="row">
    <a class="btn btn-success btn-large col-md-6 col-md-offset-3" data-toggle="modal" data-remote="<%= new_group_path %>" data-target=".bs-example-modal-sm">Create your own group!</a>
</div>

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      
    </div>
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
    
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    
      <a class="navbar-brand" href="<%= root_path %>"><%= image_tag "logo.png", size: "180x35", class: "text-center logo" %></a>

      <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Groups<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% if current_user %>
              <% if current_groups.length >= 1 %>
                <li class="divider"></li>
                <% current_groups.each do |g|  %>
                  <li> 
                  <%= link_to( g.name, group_categories_url(g), data: { no_turbolink: true}) %> 
                  </li>
                <% end %>
              <% end %>
            <% end %>
            <li class="divider"></li>
            <li><a href="<%= new_group_path %>">Create New Group</a></li>
          </ul>
        </li>
        <li>
          <%= link_to "Log out", session_path, method: :delete, class: "pull-right" %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>