config/routes.rb
Wefridgerator::Application.routes.draw do
  get "invitees/new"
  root 'users#new'

  resources :users

  resource :session, only: [:new, :create, :destroy]

  resources :static_pages 
  
  post "categories/:category_id/items/:id/update" => "items#update_item", as: :update_item
  get "categories/:id/items/new_item" => "items#new_container_item", as: :new_container_item
  get "categories/:id/items/new_sl" => "items#new_shopping_list_item", as: :new_shopping_list_item
  # get "categories/api/"  => "categories#nothing"
  get "groups/:id/api/items" => "categories#item_json"
  #delete "containers/:id/api/items" => "items#destroy"
  delete "categories/:category_id/items/:id" => "items#destroy"
  post "categories/:id/items/speech" => "items#create_speech", as: :new_speech_item


  resources :groups do
    resources :invitees
    resources :user_groups
    resources :receipts
    resources :categories
    resources :arts
    resources :messages
  end

  resources :categories do
    resources :items, only: [:index, :show, :create, :edit, :update, :destroy]
  end

end

app/models/art.rb
class Art < ActiveRecord::Base
  belongs_to :user
  belongs_to :container
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items
  belongs_to :group
end

app/models/chatroom.rb
class Chatroom < ActiveRecord::Base
	has_many :messages

  belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :shopping_lists
	has_many :categories
	has_many :receipts
  has_many :arts
  has_many :invitees
  has_many :items, through: :categories
  has_many :messages
  # belongs_to :user_groups
  has_many :user_groups
	has_many :users, through: :user_groups

end

app/models/invitee.rb
class Invitee < ActiveRecord::Base
  belongs_to :group
end

app/models/item.rb
class Item < ActiveRecord::Base
  
  belongs_to :category
  belongs_to :user
  belongs_to :group

  
  # validates :name, presence: true
  # validates :quantity, {presence: true, numericality: true}
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/shopping_list.rb
class ShoppingList < ActiveRecord::Base
	has_many :items
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :arts
	has_many :receipts
	has_many :messages
	has_many :shopping_lists
  has_many :items
  
  # belongs_to :user_groups
  has_many :user_groups
  has_many :groups, through: :user_groups

	has_secure_password 

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :get_category, only: [:index, :show, :edit, :create, :update, :destroy]
  skip_before_filter  :verify_authenticity_token
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new_container_item
    @item = Item.new

    @category = Category.find(params[:id])

  end

  def new_shopping_list_item
    @item = Item.new
    @category = Category.find(params[:id])
  end

  def create
    @item = @category.items.new(item_params)
    @item.user = current_user
    @item.container_type = params[:container_type]
    #This container type refers to the param name we put in the Items show view
    @item.container_type = "Shopping List" if @item.container_type == nil
    #Assigns container type to items dropped in the shopping list

    if @item.save
      
      redirect_to group_categories_path(@category.group_id)
    else
      render 'new'
    end
  end

  def create_speech
    @category = Category.find(params[:id])
    @item = Item.new(item_params)
    @item.user = current_user
    @item.category = @category
    @item.container_type = "Refridgerator"

    # respond_to do |format|
    #   if @item.save
    #     format.html { redirect_to @item, notice: 'item was successfully created.' }
    #     format.json { render json: @item, status: :created, location: @item }
    #   else
    #     format.html { redirect_to: new_group_path }
    #     format.json { render json: @item.errors, status: :unprocessable_entity }
    #   end
    # end

    if @item.save
      @item_saved = "it saved"
      redirect_to "group_categories_path(@group)"
    else
      @item_saved = "it didn't save"
      redirect_to "new_group_path"
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(item_params)
      @item.update_attribute(:container_type, change_container(@item))
      redirect_to group_categories_path(@category.group_id)
    else
      render 'edit'
    end
  end

  def update_item
    @category = Category.find(params[:category_id])
    @item = Item.find(params[:id])
    @item.update_attribute(:container_type, change_container(@item))
    @item.update_attribute(:exp_date, nil)
    #change_container(@item)
    redirect_to group_categories_path(@category.group_id)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to group_categories_path(@category.group_id)
  end

  private
  def item_params
    params.require(:item).permit(:name, :category_id, :container_type, :user_id, :exp_date, :quantity, :is_private)
  end

  def get_category
    @category = Category.find(params[:category_id])
  end

  def change_container(item)
    if item.container_type == "Refridgerator" || item.container_type == "Freezer" || item.container_type == "Pantry"
      item.container_type = "Shopping List"
    else
      item.container_type = params[:container_type]
    end
  end

end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/invitees_helper.rb
module InviteesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_modal.html.erb
asdf

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<img src="/assets/<%= @category.image %>.png">

<h1>Add <%= @category.name %> item to your "Refridgerator"!</h1>

<%= form_for @item, {url: category_item_path(@category, @item)} do |f| %>
<%= f.text_field :name %>
<%= f.number_field :quantity, placeholder: "Quantity" %>
<%= f.date_field :exp_date, placeholder: "Expiration Date" %> 
<%= f.select :container_type, [["Refridgerator"],["Freezer"],["Pantry"]], {}, {name: "container_type", default: "select a container"} %>
<!-- name is the name of the parameter and it allows you to call that paramter from the controller. The paramter would be the container_type from that item! -->
<%= f.submit %>
<% end %>

app/views/items/index.html.erb
<div class="row">
  <div class="col-md-5 col-md-offset-1">
    <h1>Items in your kitchen</h1>
    <% @items.each do |item| %>
      <% if item.container_type != "Shopping List" %>
      <li><strong><%= item.name %></strong>
        <% if item.exp_date %> -- Expires: <%= item.exp_date.strftime("%A, %D") %><% end %> in the <%= item.container_type %>
          <%= link_to "Add to Shopping List", update_item_path(item.category_id, item) ,method: :post, class: "btn btn-success"%>
        <%= link_to "Delete item...", category_item_path(item.category_id, item), method: :delete, class: "btn btn-danger"%>
      </li>
      <% end %>
    <% end %>
  </div>
  <div class="col-md-5 col-md-offset-1">
    <h1>Items in your shopping list</h1>
    <% @items.each do |item| %>
      <% if item.container_type == "Shopping List" %>
      <li><strong><%= item.name %></strong> in the <%= item.container_type %>
    
    <button class="btn btn-success" data-toggle="modal" data-remote="<%= edit_category_item_path(item.category_id, item) %>" data-target=".bs-example-modal1-lg">Bought!</button>



        <%= link_to "Delete item...", category_item_path(item.category_id, item), method: :delete, class: "btn btn-danger"%>
      </li>
      <% end %>
    <% end %>
  </div>
</div>


<div class="modal fade bs-example-modal1-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      
    </div>
  </div>
</div>

app/views/items/new.html.erb
<%= form_for @item, {url: category_items_path(@category)} do |f| %>
<%= f.text_field :name, placeholder: "Item name" %>
<%= f.number_field :quantity, placeholder: "Quantity" %>
<%= f.date_field :exp_date, placeholder: "Expiration Date" %> 
<%= f.select :container_type, [["Refridgerator"],["Freezer"],["Pantry"]], {}, {name: "container_type", default: "select a container"} %>
<!-- name is the name of the parameter and it allows you to call that paramter from the controller. The paramter would be the container_type from that item! -->
<%= f.submit %>
<% end %>

app/views/items/new_container_item.html.erb
  <!-- Login Screen -->
  <div class="newitem">
  <div class="container-fluid" style="width: 400px">
    <h1>Add new <%= @category.name %>!<img src="/assets/<%= @category.image %>.png"></h1> 
 	    <%= form_for @item, {url: category_items_path(@category)} do |f| %>
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-pencil"></i></span>
            <%= f.text_field :name, :class => "form-control",:placeholder => "name" %>
          </div>
        </div>
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-heart"></i></span>
            <%= f.number_field :quantity, :class => "form-control", :placeholder => "Quantity" %>
          	</div>
          </div>
         <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
					Experation date
            <%=f.date_field :exp_date, placeholder: "Expiration Date" %>
        </div>
        </div>
	       <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-lock"></i></span>
         
						<%= f.select :container_type, [["Refridgerator"],["Freezer"],["Pantry"]], {}, {name: "container_type", default: "select a container"} %>
					</div>
				</div>
  			 <%= f.submit "Add item!", :class => "btn btn-lg btn-primary btn-block", data: { disable_with: "Adding..."} %>
      	<% end %>
    <button id="close" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
	</div>

app/views/items/new_item.html.erb
<%= form_for @item, {url: category_items_path(@category)} do |f| %>
<%= f.text_field :name, placeholder: "Item name" %>
<%= f.number_field :quantity, placeholder: "Quantity" %>
<%= f.date_field :exp_date, placeholder: "Expiration Date" %> 
<%= f.select :container_type, [["Refridgerator"],["Freezer"],["Pantry"]], {}, {name: "container_type", default: "select a container"} %>
<!-- name is the name of the parameter and it allows you to call that paramter from the controller. The paramter would be the container_type from that item! -->
<%= f.submit %>
<% end %>

app/views/items/new_shopping_list_item.html.erb
  <!-- Login Screen -->
  <div class="newitem">
  <div class="container-fluid" style="width: 500px">
    <h1>Add new <%= @category.name %>!<img src="/assets/<%= @category.image %>.png"></h1> 
 	    <%= form_for @item, {url: category_items_path(@category)} do |f| %>
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-pencil"></i></span>
            <%= f.text_field :name, :class => "form-control",:placeholder => "name" %>
          </div>
        </div>
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-heart"></i></span>
            <%= f.number_field :quantity, :class => "form-control", :placeholder => "Quantity" %>
            <%= f.check_box :is_private %> Make item private? (only you will see items in your private list)
          	</div>
          </div>
  
	
  			 <%= f.submit "Add item!", :class => "btn btn-lg btn-primary btn-block", data: { disable_with: "Adding..."} %>
      	<% end %>
<button id="close" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
	</div>

app/views/items/shoppinglist.html.erb
<%= form_for @item, {url: category_items_path(@category)} do |f| %>
<%= f.text_field :name, placeholder: "Item name" %>
<%= f.number_field :quantity, placeholder: "Quantity" %>
<% f.date_field :exp_date, placeholder: "Expiration Date" %> 
<%# f.select :container_type, [["Shopping List"]], {}, {name: "container_type"} %>
<!-- name is the name of the parameter and it allows you to call that paramter from the controller. The paramter would be the container_type from that item! -->
<%= f.submit %>
<% end %>

app/views/items/show.html.erb
<h3><%= @item.name %></h3><br>
Quantity: <%= @item.quantity %><br>
<% if @item.exp_date %>
  Expiration Date: <%= @item.exp_date %><br>
<% end %>
Container Type: <%= @item.container_type %><br>
Who put it in the <%= @item.container_type %> ???: <%= @item.user.first_name %><br>
private item?!!!?: <%= @item.is_private %><br> 