config/routes.rb
Wefridgerator::Application.routes.draw do
  get "invitees/new"
  root 'users#new'

  resources :users

  resource :session, only: [:new, :create, :destroy]

  resources :static_pages 
  
  post "categories/:category_id/items/:id/update" => "items#update_item", as: :update_item
  get "categories/:id/items/new_item" => "items#new_container_item", as: :new_container_item
  get "categories/:id/items/new_sl" => "items#new_shopping_list_item", as: :new_shopping_list_item
  # get "categories/api/"  => "categories#nothing"
  get "groups/:id/api/items" => "categories#item_json"
  #delete "containers/:id/api/items" => "items#destroy"
  delete "categories/:category_id/items/:id" => "items#destroy"
  post "categories/:id/items/speech" => "items#create_speech", as: :new_speech_item


  resources :groups do
    resources :invitees
    resources :user_groups
    resources :receipts
    resources :categories
    resources :arts
    resources :messages
  end

  resources :categories do
    resources :items, only: [:index, :show, :create, :edit, :update, :destroy]
  end

end

app/models/art.rb
class Art < ActiveRecord::Base
  belongs_to :user
  belongs_to :container
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items
  belongs_to :group
end

app/models/chatroom.rb
class Chatroom < ActiveRecord::Base
	has_many :messages

  belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :shopping_lists
	has_many :categories
	has_many :receipts
  has_many :arts
  has_many :invitees
  has_many :items, through: :categories
  has_many :messages
  # belongs_to :user_groups
  has_many :user_groups
	has_many :users, through: :user_groups

end

app/models/invitee.rb
class Invitee < ActiveRecord::Base
  belongs_to :group
end

app/models/item.rb
class Item < ActiveRecord::Base
  
  belongs_to :category
  belongs_to :user
  belongs_to :group

  
  # validates :name, presence: true
  # validates :quantity, {presence: true, numericality: true}
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/shopping_list.rb
class ShoppingList < ActiveRecord::Base
	has_many :items
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :arts
	has_many :receipts
	has_many :messages
	has_many :shopping_lists
  has_many :items
  
  # belongs_to :user_groups
  has_many :user_groups
  has_many :groups, through: :user_groups

	has_secure_password 

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


  def index 
    @group = Group.find(params[:group_id])
    @message = Message.new
    @categories = Category.where(:group_id => @group)
    @item = Item.new
    @items = Item.all
    @shopping_list_items = Item.where(:container_type => "Shopping List")
    @category_array = @categories.all.map { |f|
        { id: f.id, name: f.name, image: f.image} }.to_json
    @other_category = @categories.where(name: "Other").first
  
    respond_to do |format|
     format.html
     format.js
    end
  end
  
  def show
  end

  def new
    @category = Category.new
    @item = Item.new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end


  def item_json
    # @container = Container.find(params[:id])
    @categories = Category.where(:group_id => @group)
    @items = render json: Item.where(category_id: @categories.map(&:id))
  end


end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/invitees_helper.rb
module InviteesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_messages.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @message,  {url: group_messages_path(@group), :remote => true}  do |f| %>
      <div class="form-group">
        <%= f.text_field :comment, class:"form-control", :placeholder => "Write a comment..." %>
        <% f.button "Add comment",  class:"btn btn-primary btn-lg", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Adding..."} %>
      </div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="scroll col-md-6 col-md-offset-3">
    <% @group.messages.reverse.each do |c| %>
      <li><b><%= c.user.first_name %>: </b><%= c.comment %></li>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<style>
  * {
    font-family: Verdana, Arial, sans-serif;
  }
  a:link {
    color:#000;
    text-decoration: none;
  }
  a:visited {
    color:#000;
  }
  a:hover {
    color:#33F;
  }
  .button {
    background: -webkit-linear-gradient(top,#008dfd 0,#0370ea 100%);
    border: 1px solid #076bd2;
    border-radius: 3px;
    color: #fff;
    display: none;
    font-size: 13px;
    font-weight: bold;
    line-height: 1.3;
    padding: 8px 25px;
    text-align: center;
    text-shadow: 1px 1px 1px #076bd2;
    letter-spacing: normal;
  }
  .center {
    padding: 10px;
    text-align: center;
  }
  .final {
    color: black;
    padding-right: 3px; 
  }
  .interim {
    color: gray;
  }
  .info {
    font-size: 14px;
    text-align: center;
    color: #777;
    display: none;
  }
  .right {
    float: right;
  }
  .sidebyside {
    display: inline-block;
    width: 45%;
    min-height: 40px;
    text-align: left;
    vertical-align: top;
  }
  #headline {
    font-size: 40px;
    font-weight: 300;
  }
  #info {
    font-size: 20px;
    text-align: center;
    color: #777;
    visibility: hidden;
  }
  #results {
    font-size: 14px;
    font-weight: bold;
    border: 1px solid #ddd;
    padding: 15px;
    text-align: left;
    min-height: 150px;
  }
  #start_button {
    border: 0;
    background-color:transparent;
    padding: 0;
  }
</style>




<% if current_groups.include?(@group) %>
<div ng-controller="dragNdrop">

  <h1 class="center" id="headline">
    <a href="http://dvcs.w3.org/hg/speech-api/raw-file/tip/speechapi.html">
      Web Speech API</a> Demonstration</h1>
    <div id="info">
      <p id="info_start">Click on the microphone icon and begin speaking.</p>
      <p id="info_speak_now">Speak now.</p>
      <p id="info_no_speech">No speech was detected. You may need to adjust your
        <a href="//support.google.com/chrome/bin/answer.py?hl=en&amp;answer=1407892">
          microphone settings</a>.</p>
      <p id="info_no_microphone" style="display:none">
        No microphone was found. Ensure that a microphone is installed and that
        <a href="//support.google.com/chrome/bin/answer.py?hl=en&amp;answer=1407892">
        microphone settings</a> are configured correctly.</p>
      <p id="info_allow">Click the "Allow" button above to enable your microphone.</p>
      <p id="info_denied">Permission to use microphone was denied.</p>
      <p id="info_blocked">Permission to use microphone is blocked. To change,
        go to chrome://settings/contentExceptions#media-stream</p>
      <p id="info_upgrade">Web Speech API is not supported by this browser.
         Upgrade to <a href="//www.google.com/chrome">Chrome</a>
         version 25 or later.</p>
    </div>
    <div class="right">
      <button id="start_button" ng-click="startButton(event)">
        <img id="start_img" src="assets/mic.gif" alt="Start"></button>
    </div>
    <div id="results">
      <span id="final_span" class="final"></span>
      <span id="interim_span" class="interim"></span>
      <p>
    </div>
    <div class="center">
      <div class="sidebyside" style="text-align:right">
        <button id="copy_button" class="button" ng-click="copyButton()">
          Copy and Paste</button>
        <div id="copy_info" class="info">
          Press Control-C to copy text.<br>(Command-C on Mac.)
        </div>
      </div>
      <div class="sidebyside">
        <button id="email_button" class="button" onclick="emailButton()">
          Create Email</button>
        <div id="email_info" class="info">
          Text sent to default email application.<br>
          (See chrome://settings/handlers to change.)
        </div>
      </div>
      <div id="div_language">
        <select id="select_language" onchange="updateCountry()"></select>
        &nbsp;&nbsp;
        <select id="select_dialect"></select>
      </div>
    </div>
  </div>



	<div id="dd-elements">
		<div id="drag-elements">

      <!-- initializes current groups id -->
      <p ng-init="group = <%= @group.id %>"></p>
      <p ng-init="othercat = <%= @other_category.id %>"></p>

        <!-- initalizes category array -->
			<p ng-init="cats = <%= @category_array %>"></p>
			<div class="container">
			 
        <!-- Back a page in pagination -->
      Result: <%= @item_saved %>
      <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center food-items">
  				<a ng-repeat='c in active_cats()| orderBy:"name":false' ng-href'{{dropZoneLink}}'>
  					<div class="col-md-6 col-md-offset-3 category" draggable="true" ng-mousedown="setCategory(c.id)">
  						<div id="info">	<img ng-src="/assets/{{c.image}}.png">
  						  <div id="dropdown">{{c.name}}</div>				
  					  </div>
  					</div>
  				</a>
        </div>
      </div>
        <!-- Advance page in pagination -->
      <div class="row">
        <div class="col-md-6">
          <div class="btn btn-primary col-md-1 col-md-offset-5" ng-show="start_button" ng-click="page_move(-5)">&lt;&lt;</div>
        </div>
        <div class="col-md-6 ">
          <div class="btn btn-primary col-md-1 col-md-offset-5" ng-show="end_button" ng-click="page_move(5)">&gt;&gt;</div>
        </div>
      </div>
		</div>
	</div>
</div> 




<!-- items index -->
<div class="row">
  <div class="col-md-3 col-md-offset-1">
    <h1 class="container-list-title text-center"><%= @group.name %> Items</h1>
    <div class="btn btn-primary btn-sm" ng-click="filter('All')">All Items</div>
    <div class="btn btn-primary btn-sm" ng-click="filter('Refridgerator')">Refridgerator</div>
    <div class="btn btn-primary btn-sm" ng-click="filter('Freezer')">Freezer</div>
    <div class="btn btn-primary btn-sm" ng-click="filter('Pantry')">Pantry</div>

    <% @items.each  do |item| %>
    
      <% item_group = item.category.group.id %>
      <% if item_group == @group.id %>
  
      <% if item.container_type != "Shopping List" %>
      
        <li ng-show='filter_view == "All" || filter_view == "<%= item.container_type %>"'>
          <div class="col-md-2 item-image-mini">
            <%= image_tag item.category.image + ".png", class: "img-responsive", size: "30x30" %>
          </div>
          <div class="col-md-10">
            <div class="item-name"><%= item.name %></div><br>in <b><%= item.container_type %></b>  <% if item.exp_date %>, <b>Expires:</b> <%= item.exp_date.strftime("%A, %D") %><% end %>
            <%= link_to " x ", category_item_url(item.category_id, item), method: :delete, data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Deleting..."}, class: "btn btn-danger btn-xs pull-right"%>
            <%= link_to " + ", update_item_url(item.category_id, item) ,method: :post, data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Adding to Shopping List..."}, class: "btn btn-warning btn-xs pull-right"%>
          </div>
        </li>
      <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="col-md-4">
  	<div class="col-md-6 text-center">
  		<p class="container-title">Add to Kitchen</p>
      <div id="drop-target-one"></div>
  	</div>
  	
  	<div class="col-md-6 text-center">
  		<p class="container-title">Add to Shopping List</p>
      <div id="drop-target-two"></div>
  	</div>
  
  </div>
 <div class="col-md-4">
    <h1 class="container-list-title text-center">Shopping list</h1>

    <% @shopping_list_items.each do |item| %>
  
 <% item_group = item.category.group.id %>
      <% if item_group == @group.id %>
    <% if item.container_type == "Shopping List" %>
      <li><strong><%= item.name %></strong>  
    
    <button class="btn btn-success btn-xs" data-toggle="modal" data-remote="<%= edit_category_item_url(item.category_id, item) %>" data-target=".bs-example-modal1-lg">Bought!</button>

        <%= link_to "x", category_item_url(item.category_id, item), method: :delete, data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Deleting..."}, class: "btn btn-danger btn-xs"%>
      </li>
      <% end %>
    <% end %>
    <% end %>
  </div>
</div>
</div>



<!-- items index -->

 
 


<div class="modal fade bs-example-modal1-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      
    </div>
  </div>
</div>

</div>
<% else %>
  <%= render 'partials/create_group' %>
<% end %>


<br>


<div class="container">

  <div id="messages">
    <%= render 'messages' %>
  </div>
  </div>
  </div>

app/views/categories/index.js.erb
$('#messages').html("<%=j render 'messages' %>");

app/views/categories/item_json.html.erb
<%= @items %>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>